# Generated by Django 2.2 on 2020-01-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='Post body'),
            preserve_default=False,
        ),
    ]
